function Hd = untitled
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 05-Aug-2022 03:55:22

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

N  = 4;     % Order
Fc = 0.02;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc);
Hd = design(h, 'butter', 'FilterStructure', 'df1sos');

% Get the transfer function values.
[b, a] = tf(Hd);
b
a

% Convert to a singleton filter.
Hd = dfilt.df1(b, a);

% Convert the filter to the Direct-Form II structure.
Hd = convert(Hd, 'df2');

% [EOF]
